### ISSUE TITLE
Continuous Integration(GitHub Actions)

### ISSUE THREAD

**Issue by ChristianPanov** [ChristianPanov/lwlog#35]

**Comment by aeropl3b** [comment]
As far as language support for different CI platforms, they are all more or less the same for C++. They run containerized environments that you need to install deps on and then run whatever scripts you want. Since CMake has really nice utilities in ctest for running CI workflows, you can write once run anywhere, which is now available on dev :)

The major differences between CI providers is what support they provide for CI platforms, ie. Linux, Mac, and Windows machines, and how the charge for use of the systems. Linux is pretty ubiquitous and cheap, but good Mac and Windows support is a little harder, but also way better that it used to be.
